### ISSUE TITLE
Could not create schema migrations table error

### ISSUE THREAD

**Issue by euphbriggs** [mjaric/ecto_sql#3] opened 2020-01-29 21:48 UTC
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 21 [erts-10.2] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Elixir 1.9.4 (compiled with Erlang/OTP 20)
```

* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.):
**SQL Server 12.0.6024**

* Ecto version (mix deps):

```
ecto 3.3.2 (Hex package) (mix)
  locked at 3.3.2 (ecto) 002aa428
```

* Database adapter and version (mix deps):
```
* tds 2.1.0 (https://github.com/livehelpnow/tds) (mix)
  locked at 90bb001 (branch: master)
  ok
* ecto_sql 3.3.2 (https://github.com/mjaric/ecto_sql) (mix)
  locked at 035017b (branch: tds-support)
  ok
```
* Operating system:

**Windows 10**

### Current behavior

When I'm starting from a fresh database (the database has been created, but no tables exist) and run `mix ecto.reset` I get the following error. The strange thing, is that the "schema_migrations" table does get created, but nothing else happens.

```
15:42:11.353 [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table for managing migrations:

    config :rti, Rti.Repo,
      migration_source: "some_other_table_for_schema_migrations"

The full error report is shown below.

** (Tds.Error) Line 1 (Error 2714): There is already an object named 'schema_migrations' in the database.
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql) lib/ecto/adapters/sql.ex:719: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql) lib/ecto/migrator.ex:635: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql) lib/ecto/migrator.ex:479: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql) lib/ecto/migrator.ex:613: anonymous fn/5 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/ecto/migrator.ex:612: Ecto.Migrator.migrate/4
    (ecto_sql) lib/ecto/migrator.ex:149: Ecto.Migrator.with_repo/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:117: anonymous fn/5 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:105: Mix.Tasks.Ecto.Migrate.run/2
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

### Expected behavior

After the migrations table was created, I exected the migrations that are defined to get executed.

### Additional Information

I'm migrating from using mssqlex/mssql_ecto where the migrations worked. I'm not sure if that's helpful information or not, but I thought I'd mention it just in case.

**Comment by mjaric** [comment] 2020-01-30 12:05
Found the issue, you should be ok now if you update to latest commit

**Comment by euphbriggs** [comment] 2020-01-30 12:16
Awesome! Thank you! I have a new error now. I'm not being sarcastic btw, I'm genuinely excited.

# Output
```
06:08:40.941 [info]  == Running 20200114170819 Rti.Repo.Migrations.CreatePeriods.change/0 forward

06:08:40.941 [info]  create table periods

06:08:40.947 [info]  == Migrated 20200114170819 in 0.0s
** (Tds.Error) Line 1 (Error 8115): Arithmetic overflow error converting expression to data type int.
    (ecto_sql) lib/ecto/adapters/sql.ex:629: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql) lib/ecto/adapters/sql.ex:562: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (ecto_sql) lib/ecto/migrator.ex:485: anonymous fn/3 in Ecto.Migrator.lock_for_migrations/4
    (ecto_sql) lib/ecto/migrator.ex:488: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql) lib/ecto/migrator.ex:613: anonymous fn/5 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/ecto/migrator.ex:612: Ecto.Migrator.migrate/4
    (ecto_sql) lib/ecto/migrator.ex:149: Ecto.Migrator.with_repo/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:117: anonymous fn/5 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:105: Mix.Tasks.Ecto.Migrate.run/2
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

# CreatePeriods migration

This migration succeeds. The next one is the one that fails.

```Elixir
defmodule Rti.Repo.Migrations.CreatePeriods do
  use Ecto.Migration

  def change do
    create table(:periods) do
      add(:end, :date)
      add(:period, :integer)
      add(:start, :date)
      add(:year, :integer)

      timestamps()
    end
  end
end
```

# CreateDayparts

Could it be from the way I'm creating a non-standard primary key? I'm matching an existing database's naming convention to keep the cognitive overhead between the two system low.

```Elixir
defmodule Rti.Repo.Migrations.CreateDayparts do
  use Ecto.Migration

  def change do
    create table(:dayparts, primary_key: false) do
      add(:DayPartID, :integer, primary_key: true)
      add(:Description, :string)

      timestamps()
    end
  end
end
```

**Comment by mjaric** [comment] 2020-01-30 15:00
should be ok now

**Comment by euphbriggs** [comment] 2020-01-30 15:34
The migrations have completed now! Thank you!

# Output

The new issue is occurring when seeding the database. It fails on the first record it's trying to insert.

```
[debug] QUERY OK source="periods" db=0.0ms idle=109.0ms
SELECT p0.[id], p0.[end], p0.[period], p0.[start], p0.[year], p0.[inserted_at], p0.[updated_at] FROM [periods] AS p0 WHERE (p0.[id] = @1) [1]
[debug] QUERY ERROR db=0.0ms idle=109.0ms
INSERT INTO [periods] ([end], [period], [start], [year], [inserted_at], [updated_at]) OUTPUT INSERTED.[id] VALUES (@1, @2, @3, @4, @5, @6) [~D[2018-01-30], 1, ~D[2018-01-03], 2018, {{2020, 1, 30}, {15, 26, 21}}, {{2020, 1, 30}, {15, 26, 21}}]
** (CaseClauseError) no case clause matching: {:error, %FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :date_to_gregorian_days, kind: nil, module: :calendar}}
    (ecto_sql) lib/ecto/adapters/mssql/connection.ex:88: Ecto.Adapters.MsSql.Connection.query/4
    (ecto_sql) lib/ecto/adapters/sql.ex:666: Ecto.Adapters.SQL.struct/10
    (ecto) lib/ecto/repo/schema.ex:655: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:263: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:783: Enum.each/2
    (elixir) lib/code.ex:813: Code.require_file/2
    (mix) lib/mix/tasks/run.ex:145: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (mix) lib/mix/task.ex:365: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:292: Mix.Task.run/2
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

# Seed sample

This is a sample from `priv/repo/seeds.exs`. Its 

```Elixir
alias Rti.Period

# Make sure the application has started up
{:ok, _} = Application.ensure_all_started(:logger)

[
  # 2018
  %{id: 1, year: 2018, period: 1, start: ~D[2018-01-03], end: ~D[2018-01-30]},
  %{id: 2, year: 2018, period: 2, start: ~D[2018-01-31], end: ~D[2018-02-27]},
  %{id: 3, year: 2018, period: 3, start: ~D[2018-02-28], end: ~D[2018-04-03]},
]
|> Enum.each(fn record ->
  case Rti.Repo.get(Period, record.id) do
    nil ->
      %Period{}
      |> Period.changeset(record)
      |> Rti.Repo.insert()

    _ ->
      nil
  end
end)
```

# Rti.Period

```Elixir
defmodule Rti.Period do
  use Ecto.Schema
  import Ecto.Changeset

  schema "periods" do
    field :end, :date
    field :period, :integer
    field :start, :date
    field :year, :integer

    timestamps()
  end

  @doc false
  def changeset(period, attrs) do
    period
    |> cast(attrs, [:period, :year, :start, :end])
    |> validate_required([:period, :year, :start, :end])
  end
end
```

**Comment by mjaric** [comment] 2020-01-30 16:51
That is about missing date converter. I'll post update when it is ok.

Thanks!

**Comment by mjaric** [comment] 2020-01-30 17:00
ok, seed should work now, just `mix deps.update tds` but I think I have to add some loaders and dumpers in MSSQL adapter in ecto_sql so `:date` column type is mapped to %Date{} in case it yields erl date format.

**Comment by euphbriggs** [comment] 2020-01-30 17:11
That fixes my migration and seeding issues. Thank you very much! I'll keep an eye out for the updates that you mentioned.

Do you want to leave this issue open until you have the loaders and dumpers complete or go ahead and close it since the reported issue is resolved?

**Comment by mjaric** [comment] 2020-01-30 19:07
yes, lets leave it for now.

BTW, I added loaders so your models get `%Date{}`  and `Time` values instead of erlang tuple. Just `mix deps.update ecto_sql` and it should work

**Comment by euphbriggs** [comment] 2020-01-30 19:26
The initial testing is working. I'll start back on the active development of my project tomorrow and let you know if anything turns up.

**Comment by mjaric** [comment] 2020-02-09 16:36
I think that adapter is now in very good shape. I will close this issue, so any new should be added either to [PR in ecto_sql repo](https://github.com/elixir-ecto/ecto_sql/pull/184) or [TDS repo](https://github.com/livehelpnow/tds/issues) depending to which library the issue is related.

@euphbriggs thanks for your help!

**Closed as completed by mjaric** 2020-02-09 16:36 UTC
